### ISSUE TITLE
Weird Display Issues Off Screen

### ISSUE THREAD

**Issue by Soutarmark** [DerKoun/bsnes-hd#121] opened 2023-02-20 03:28 UTC
I was playing a Link to the past and am having weird issues with with parts of the game displaying outside the widescreen view:
![zelda](https://user-images.githubusercontent.com/39926228/220002760-d6292a51-99b4-4d07-a6f8-c8ffac3c177e.jpg)

I had played with the setting with no luck so far.

**Comment by DerKoun** [comment] 2023-02-24 20:31
Games without widescreen patches in non-Mode7 scenes don't display widescreen backgrounds correctly as the games were not designed for it and many are optimized to only handle the area that's normally visible. You'll get lucky in some, but many will be more confusing than enjoyable.
I'll close this issue, as it is not a bug. If you want to chat further you can join the Discord linked in the readme.

**Closed** 2023-02-24 20:31 UTC
