### ISSUE TITLE
Background moved 4px to the right in 16:10 and 21:9

### ISSUE THREAD

**Issue by wojpawlik** [DerKoun/bsnes-hd#60] opened 2020-10-03 18:47 UTC
### 16:9
![Super Mario World (USA)-16_9](https://user-images.githubusercontent.com/23058303/94999252-8b0df080-05b8-11eb-88be-ccb3a87ab416.png)

### 2:1
![Super Mario World (USA)-2_1](https://user-images.githubusercontent.com/23058303/94999281-ad077300-05b8-11eb-990b-0cf919d59ab7.png)

### 21:9
![Super Mario World (USA)-21_9](https://user-images.githubusercontent.com/23058303/94999355-19827200-05b9-11eb-89bd-e38d744e8e22.png)

### 16:10
![Super Mario World (USA)-16_10](https://user-images.githubusercontent.com/23058303/94999361-21421680-05b9-11eb-80d0-197cef338896.png)

**Comment by DerKoun** [comment] 2020-10-05 19:12
The offset seems to be the remainder of dividing the widescreen area width by 8. Didn't find the cause at a quick glance at the code, but I'll look into it in detail.
Can I assume that the scale factor make no difference?

**Comment by wojpawlik** [comment] 2020-10-06 10:04
Yes, scale factor (Settings > Size) makes no difference.

**Comment by wojpawlik** [comment] 2020-10-06 10:04
Yes, scale factor (Settings > Size) makes no difference.

**Comment by DerKoun** [comment] 2021-02-20 22:15
Fixed in new beta 10.4
The widescreen area size is now always rounded to a multiple of 8.
@wojpawlik Can you please confirm the issue is solved completely?

**Closed by DerKoun** 2021-02-20 22:15 UTC

**Comment by wojpawlik** [comment] 2021-02-21 12:14
Confirming fix:
![obraz](https://user-images.githubusercontent.com/23058303/108624657-8bfbcd80-7446-11eb-801a-776e3f806da4.png)
![obraz](https://user-images.githubusercontent.com/23058303/108624664-93bb7200-7446-11eb-8c7b-0d99abe6062b.png)

**Comment by wojpawlik** [comment] 2021-02-21 16:11
Curious (not complaining), why did the scanline shader turn on after 10.3 -> 10.4 upgrade, even tho it's not listed?
 
![obraz](https://user-images.githubusercontent.com/23058303/108630884-7945c080-7467-11eb-82aa-5306c436f896.png)

**Comment by DerKoun** [comment] 2021-02-21 20:16
That's actually the widescreen marker being rendered incorrectly for scales of 2 or higher. I have pushed another hotfix for that. Thanks for reporting.
