### ISSUE TITLE
I can't launch on arch linux

### ISSUE THREAD

**Issue by kweonsunho** [DerKoun/bsnes-hd#61] opened 2020-10-27 14:57 UTC
I can't launch the excute file on arch linux. What will i do?

**Comment by DerKoun** [comment] 2020-10-27 21:45
You can try this Linux build: https://github.com/DerKoun/bsnes-hd/issues/11#issuecomment-596469072
Please report back, if it helps. 
If it doesn't, you must provide as much information about the issues as possible, at least all error messages.
If this is not a bug report but a request for help, please close it and join the discord, see: https://github.com/DerKoun/bsnes-hd#bsnes-hd-beta-103

**Closed** 2020-10-28 21:47 UTC
