### ISSUE TITLE
Line byproduct  

### ISSUE THREAD

**Issue by JimPancakes** [DerKoun/bsnes-hd#39] opened 2020-03-25 20:11 UTC
Sorry if this is the wrong place for this. I was just wondering if there is any way to get rid of the line that shows up on the right side of the screen:

![Terranigma (Europe)-200325-220527](https://user-images.githubusercontent.com/62670723/77581298-26295d80-6ee6-11ea-8ab0-cb9c86dac4b7.png)

I've seen this phenomenon with games that go beyond their original resolution. 

When the Aspect ratio is set to none the line no longer shows up at the price of widescreen of course. Could it be possible to implement some sort of adaptive aspect ratio that goes to 16:9 only when Mode 7 is detected or something like that?

**Comment by DerKoun** [comment] 2020-03-25 20:50
Please see https://github.com/DerKoun/bsnes-hd#widescreen-widescreen-mode
> ### Widescreen (WideScreen Mode)
> Enables experimental widescreen functionality
> - **none**: do not enable widescreen
> - **Mode 7**(default): enable widescreen for Mode 7 scenes (works for most games)
> - **all**: enable widescreen for all scenes (non-Mode 7 scenes only work acceptable in some games, but many have mostly artifacts)

Does this already cover your request?

**Comment by JimPancakes** [comment] 2020-03-25 21:31
> Please see https://github.com/DerKoun/bsnes-hd#widescreen-widescreen-mode
> Does this already cover your request?

I'm having that line with Mode 7 selected in the widescreen menu. I've toyed with it a bit and I saw what it does. The line only disappears when the aspect ratio is set to none but then I have no widescreen.

**Comment by DerKoun** [comment] 2020-03-25 21:59
I'll look into it. But I'll have this at low priority at the moment.

**Comment by JimPancakes** [comment] 2020-03-25 22:01
That's fair. Thanks!

**Comment by JimPancakes** [comment] 2021-05-16 12:07
Me again. If possible, please fix this in the next release.

**Comment by DerKoun** [comment] 2021-05-16 16:32
The roadmap for the next release is pretty set.
But if you want to help getting this issue solved sooner you can provide more information:

- What games are affected and which ones are not? A handful of each is enough. Please also add whether all scenes are affected or only certain ones.
- What are your exact settings? Screen-shots of the settings would be ideal.
- What version of bsnes-hd do you use and in what environment (OS, any special hardware)?
- Please provide some screen-shots showing the issue in the latest version.

If I can easily reproduce the issue I may be able to resolve it in the following release.

**Comment by JimPancakes** [comment] 2021-05-18 20:08
bsnes-hd beta 10.4 used
Windows 10 Home 64-bit - Version: 20H2 - OS build: 19042.985
No special hardware.
GPU - Nvidia GTX 1660 Ti - Driver version: 465.89
CPU - AMD Ryzen 5 3600
RAM - 16 GB DDR4 

Settings are default:

![settings_01](https://user-images.githubusercontent.com/62670723/118705672-2e96d300-b821-11eb-8494-15f5ba5adb7d.png)
![settings_02](https://user-images.githubusercontent.com/62670723/118705676-2f2f6980-b821-11eb-9be1-b0ac0e0ea31f.png)
![settings_03](https://user-images.githubusercontent.com/62670723/118705678-2fc80000-b821-11eb-86fb-a0a4f566edbf.png)

Screenshots were taken in windowed mode with these settings (the problem does show up in fullscreen as well, don't worry):

![settings_04](https://user-images.githubusercontent.com/62670723/118705884-70c01480-b821-11eb-834d-718f9876787f.png)
![settings_05](https://user-images.githubusercontent.com/62670723/118705885-7158ab00-b821-11eb-9d68-4d8f0deea44c.png)
![settings_06](https://user-images.githubusercontent.com/62670723/118705886-7158ab00-b821-11eb-9fe0-d61984067a6e.png)

In any of the games tested the problem never shows up during Mode 7 sequences (when the game actually goes widescreen).



**Kirby's Dream Land 3 (USA)**

The line first shows up in the intro animation for GRASS LAND (nothing before that):


![Kirby's Dream Land 3 (USA)-001](https://user-images.githubusercontent.com/62670723/118709271-6f90e680-b825-11eb-94d6-c7b5ed6a6248.png)

It then shows up in gameplay but it doesn't go all the way down, not covering the stats segment of the screen (harder to see but it's there):

![Kirby's Dream Land 3 (USA)-002](https://user-images.githubusercontent.com/62670723/118709961-52104c80-b826-11eb-89c4-2e8aa6709fcb.png)

Interestingly the transition animation does cover it:

![Kirby's Dream Land 3 (USA)-003](https://user-images.githubusercontent.com/62670723/118710716-55f09e80-b827-11eb-8245-7acc4bfd3e26.png)


**Super Mario RPG - Legend of the Seven Stars (USA)**

It first shows up in the intro:

![Super Mario RPG - Legend of the Seven Stars (USA)-001](https://user-images.githubusercontent.com/62670723/118711049-c4cdf780-b827-11eb-9415-d974ad45c039.png)

And the slowly disappears as the screen darkens:

![Super Mario RPG - Legend of the Seven Stars (USA)-002](https://user-images.githubusercontent.com/62670723/118711197-fa72e080-b827-11eb-8ccd-4ea89072a033.png)

Does not show up in the title screen or the save select. Shows up again here:

![Super Mario RPG - Legend of the Seven Stars (USA)-003](https://user-images.githubusercontent.com/62670723/118711629-7b31dc80-b828-11eb-899e-cdbe056b9299.png)

It does not show up while moving about but it is present in combat:

![Super Mario RPG - Legend of the Seven Stars (USA)-004](https://user-images.githubusercontent.com/62670723/118711872-bf24e180-b828-11eb-91c2-742f7d9eb35d.png)



It also shows up in: Terranigma, Super Mario World, Super Mario World 2 - Yoshi's Island, Seiken Densetsu 3 (only in the character select and save screen as far as I saw, not in gameplay), Kirby's Dream Course.

The only one I found where it didn't show up is Contra III - The Alien Wars but I only played a bit of the first level.

Again, it never shows up in Mode 7 sections from what I saw at least. And certain elements, like text boxes or transition animations, do cover it.

It feels like a garbage pixel line. If I take any of the screenshots, resize them to the SNES's actual resolution of 256×224, then the line falls outside of this. If I set Widescreen to none in settings then the line is no more:

![Kirby's Dream Land 3 (USA)-004](https://user-images.githubusercontent.com/62670723/118715681-96065000-b82c-11eb-9da0-472bb7929fee.png)

Just a dumb suggestion from an unknowledgeable person, maybe you can make an option where the emulator switches Widescreen to Mode 7 when it detects it running and make it go to none when it's not?

If you want more screenshots and games tested please ask! Sorry if those weren't enough.

Thank you for taking an interest in this!

**Comment by DerKoun** [comment] 2021-05-19 07:08
Thank you for the detailed information. I think I found the cause (can't test right know). The background color seems to be painted one pixel to far to the right. If I can verify it this will be in fixed in the next release.

**Comment by DerKoun** [comment] 2021-05-26 20:25
Fixed in latest release (10.5). Again thanks for your efforts.

For those interested: The change is just replacing one `<=` with `<`

**Closed** 2021-05-27 08:43 UTC

**Comment by JimPancakes** [comment] 2021-05-27 15:19
Thanks a lot man! Appreciate the mention in the changelog.
All the best.

**Comment by DerKoun** [comment] 2021-05-27 18:31
> Appreciate the mention in the changelog.

You definitively spent more time on this issue than I did.
